# Generated by Django 4.1.6 on 2023-02-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='manager',
            new_name='manager_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
